#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/letsencrypt/functions"


letsencrypt_generate_certs_cmd() {
  declare desc="generates a self-signed SSL certificate/key combo"
  local cmd="certs:generate"
  [[ -z $2 ]] && dokku_log_fail "Please specify an app to run the command on"
  # verify_app_name "$2"
  # local APP="$2"; local DOMAIN="$3"; local APP_SSL_PATH="$DOKKU_ROOT/$APP/tls"

  local app="$2"; verify_app_name "$app"
  local cert_name="$3"
  local domains="$4"

  local app_root="$DOKKU_ROOT/$app"
  local le_root="$app_root/letsencrypt"
  local cert_root="$le_root/$cert_name"

  local config_dir="$(letsencrypt_configure_and_get_dir "$app" "$cert_name")"

  if [[ ! -f "$config_dir/server.key" ]] && [[ ! -f "$config_dir/server.crt" ]]; then
    local CERTS_GENERATE_TMP_WORK_DIR=$(mktemp -d "/tmp/dokku_certs.XXXXXXXXX")
    pushd "$CERTS_GENERATE_TMP_WORK_DIR" > /dev/null
    trap 'popd &> /dev/null || true; rm -rf "$CERTS_GENERATE_TMP_WORK_DIR" > /dev/null' INT TERM EXIT

    openssl genrsa -des3 -passout pass:x -out server.pass.key 2048
    openssl rsa -passin pass:x -in server.pass.key -out server.key
    openssl req -new -key server.key -out server.csr
    openssl x509 -req -days 365 -in server.csr -signkey server.key -out server.crt

    # mkdir -p "$config_dir"
    dokku_log_info1 "Installing certificate and key..."
    mv -f "$CERTS_GENERATE_TMP_WORK_DIR/server.crt" "$CERTS_GENERATE_TMP_WORK_DIR/server.csr" "$CERTS_GENERATE_TMP_WORK_DIR/server.key"  "$config_dir"
    chmod 750 "$config_dir"
    chmod 640 "$config_dir/server.crt" "$config_dir/server.csr" "$config_dir/server.key"
    # plugn trigger post-certs-update "$APP"
    # [[ -n "$DOMAIN" ]] && (domains_add "$APP" "$DOMAIN" || plugn trigger post-domains-update "$APP")
    dokku_log_info1 "The following is a certificate signing request that can be used"
    dokku_log_info1 "to generate an 'officially' signed SSL certificate for $app at $domains"
    dokku_log_info1 "by a CA of your choosing."
    cat "$config_dir/server.csr"
  else
    dokku_log_info1 "$app has an SSL endpoint already defined"
  fi
}

letsencrypt_generate_certs_cmd "$@"
