#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/letsencrypt/functions"


letsencrypt_domains_cmd() {
  #shellcheck disable=SC2034
  declare desc="set domains for a cert_name within an app"

  local app="$1"; verify_app_name "$app"
  local cert_name="$2"
  local domains="$3"

  local app_root="$DOKKU_ROOT/$app"
  local le_root="$app_root/letsencrypt"
  local cert_root="$le_root/$cert_name"

  letsencrypt_create_root "$app"

  mkdir -p $cert_root

  echo "$domains" > "$cert_root/DOMAINS"
}

letsencrypt_domains_cmd "$@"
